#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralMemo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AppraisalDb")]
	public partial class AppraisalConnectionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTb_App_Period(Tb_App_Period instance);
    partial void UpdateTb_App_Period(Tb_App_Period instance);
    partial void DeleteTb_App_Period(Tb_App_Period instance);
    partial void InsertTb_TargetEntry(Tb_TargetEntry instance);
    partial void UpdateTb_TargetEntry(Tb_TargetEntry instance);
    partial void DeleteTb_TargetEntry(Tb_TargetEntry instance);
    partial void Insertzib_appraisal_approver(zib_appraisal_approver instance);
    partial void Updatezib_appraisal_approver(zib_appraisal_approver instance);
    partial void Deletezib_appraisal_approver(zib_appraisal_approver instance);
    partial void Insertzib_workflow_master(zib_workflow_master instance);
    partial void Updatezib_workflow_master(zib_workflow_master instance);
    partial void Deletezib_workflow_master(zib_workflow_master instance);
    partial void Insertzib_appraisal_user_role(zib_appraisal_user_role instance);
    partial void Updatezib_appraisal_user_role(zib_appraisal_user_role instance);
    partial void Deletezib_appraisal_user_role(zib_appraisal_user_role instance);
    partial void Insertzib_memo_entry(zib_memo_entry instance);
    partial void Updatezib_memo_entry(zib_memo_entry instance);
    partial void Deletezib_memo_entry(zib_memo_entry instance);
    #endregion
		
		public AppraisalConnectionDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AppraisalDbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AppraisalConnectionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppraisalConnectionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppraisalConnectionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppraisalConnectionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tb_App_Period> Tb_App_Periods
		{
			get
			{
				return this.GetTable<Tb_App_Period>();
			}
		}
		
		public System.Data.Linq.Table<Tb_TargetInitiator> Tb_TargetInitiators
		{
			get
			{
				return this.GetTable<Tb_TargetInitiator>();
			}
		}
		
		public System.Data.Linq.Table<Tb_TargetEntry> Tb_TargetEntries
		{
			get
			{
				return this.GetTable<Tb_TargetEntry>();
			}
		}
		
		public System.Data.Linq.Table<zib_appraisal_approver> zib_appraisal_approvers
		{
			get
			{
				return this.GetTable<zib_appraisal_approver>();
			}
		}
		
		public System.Data.Linq.Table<zib_appraisal_dept_structure> zib_appraisal_dept_structures
		{
			get
			{
				return this.GetTable<zib_appraisal_dept_structure>();
			}
		}
		
		public System.Data.Linq.Table<zib_appraisal_approver_role> zib_appraisal_approver_roles
		{
			get
			{
				return this.GetTable<zib_appraisal_approver_role>();
			}
		}
		
		public System.Data.Linq.Table<zib_workflow_master> zib_workflow_masters
		{
			get
			{
				return this.GetTable<zib_workflow_master>();
			}
		}
		
		public System.Data.Linq.Table<zib_workflow_stage> zib_workflow_stages
		{
			get
			{
				return this.GetTable<zib_workflow_stage>();
			}
		}
		
		public System.Data.Linq.Table<zib_appraisal_user_role> zib_appraisal_user_roles
		{
			get
			{
				return this.GetTable<zib_appraisal_user_role>();
			}
		}
		
		public System.Data.Linq.Table<zib_appraisal_link_role_permission> zib_appraisal_link_role_permissions
		{
			get
			{
				return this.GetTable<zib_appraisal_link_role_permission>();
			}
		}
		
		public System.Data.Linq.Table<zib_appraisal_user_permission> zib_appraisal_user_permissions
		{
			get
			{
				return this.GetTable<zib_appraisal_user_permission>();
			}
		}
		
		public System.Data.Linq.Table<zib_memo_entry> zib_memo_entries
		{
			get
			{
				return this.GetTable<zib_memo_entry>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_App_Period")]
	public partial class Tb_App_Period : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SerialNo;
		
		private string _AppraisalYear;
		
		private string _AppraisalPeriod;
		
		private string _AppraisalTitle;
		
		private string _AppraisalStatus;
		
		private string _CurrentStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSerialNoChanging(int value);
    partial void OnSerialNoChanged();
    partial void OnAppraisalYearChanging(string value);
    partial void OnAppraisalYearChanged();
    partial void OnAppraisalPeriodChanging(string value);
    partial void OnAppraisalPeriodChanged();
    partial void OnAppraisalTitleChanging(string value);
    partial void OnAppraisalTitleChanged();
    partial void OnAppraisalStatusChanging(string value);
    partial void OnAppraisalStatusChanged();
    partial void OnCurrentStatusChanging(string value);
    partial void OnCurrentStatusChanged();
    #endregion
		
		public Tb_App_Period()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SerialNo
		{
			get
			{
				return this._SerialNo;
			}
			set
			{
				if ((this._SerialNo != value))
				{
					this.OnSerialNoChanging(value);
					this.SendPropertyChanging();
					this._SerialNo = value;
					this.SendPropertyChanged("SerialNo");
					this.OnSerialNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppraisalYear", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string AppraisalYear
		{
			get
			{
				return this._AppraisalYear;
			}
			set
			{
				if ((this._AppraisalYear != value))
				{
					this.OnAppraisalYearChanging(value);
					this.SendPropertyChanging();
					this._AppraisalYear = value;
					this.SendPropertyChanged("AppraisalYear");
					this.OnAppraisalYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppraisalPeriod", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string AppraisalPeriod
		{
			get
			{
				return this._AppraisalPeriod;
			}
			set
			{
				if ((this._AppraisalPeriod != value))
				{
					this.OnAppraisalPeriodChanging(value);
					this.SendPropertyChanging();
					this._AppraisalPeriod = value;
					this.SendPropertyChanged("AppraisalPeriod");
					this.OnAppraisalPeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppraisalTitle", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string AppraisalTitle
		{
			get
			{
				return this._AppraisalTitle;
			}
			set
			{
				if ((this._AppraisalTitle != value))
				{
					this.OnAppraisalTitleChanging(value);
					this.SendPropertyChanging();
					this._AppraisalTitle = value;
					this.SendPropertyChanged("AppraisalTitle");
					this.OnAppraisalTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppraisalStatus", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string AppraisalStatus
		{
			get
			{
				return this._AppraisalStatus;
			}
			set
			{
				if ((this._AppraisalStatus != value))
				{
					this.OnAppraisalStatusChanging(value);
					this.SendPropertyChanging();
					this._AppraisalStatus = value;
					this.SendPropertyChanged("AppraisalStatus");
					this.OnAppraisalStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentStatus", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CurrentStatus
		{
			get
			{
				return this._CurrentStatus;
			}
			set
			{
				if ((this._CurrentStatus != value))
				{
					this.OnCurrentStatusChanging(value);
					this.SendPropertyChanging();
					this._CurrentStatus = value;
					this.SendPropertyChanged("CurrentStatus");
					this.OnCurrentStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_TargetInitiators")]
	public partial class Tb_TargetInitiator
	{
		
		private string _unitcode;
		
		private string _unitname;
		
		private string _deptcode;
		
		private string _deptname;
		
		private string _initiatorname;
		
		private string _initiatornumber;
		
		private string _comments;
		
		private string _appraisalperiod;
		
		private string _hrstaffname;
		
		private string _hrstaffnumber;
		
		private System.DateTime _createdate;
		
		private System.DateTime _lasteditdate;
		
		public Tb_TargetInitiator()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitcode", DbType="VarChar(50)")]
		public string unitcode
		{
			get
			{
				return this._unitcode;
			}
			set
			{
				if ((this._unitcode != value))
				{
					this._unitcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitname", DbType="VarChar(50)")]
		public string unitname
		{
			get
			{
				return this._unitname;
			}
			set
			{
				if ((this._unitname != value))
				{
					this._unitname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string deptcode
		{
			get
			{
				return this._deptcode;
			}
			set
			{
				if ((this._deptcode != value))
				{
					this._deptcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string deptname
		{
			get
			{
				return this._deptname;
			}
			set
			{
				if ((this._deptname != value))
				{
					this._deptname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_initiatorname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string initiatorname
		{
			get
			{
				return this._initiatorname;
			}
			set
			{
				if ((this._initiatorname != value))
				{
					this._initiatorname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_initiatornumber", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string initiatornumber
		{
			get
			{
				return this._initiatornumber;
			}
			set
			{
				if ((this._initiatornumber != value))
				{
					this._initiatornumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this._comments = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appraisalperiod", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string appraisalperiod
		{
			get
			{
				return this._appraisalperiod;
			}
			set
			{
				if ((this._appraisalperiod != value))
				{
					this._appraisalperiod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hrstaffname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string hrstaffname
		{
			get
			{
				return this._hrstaffname;
			}
			set
			{
				if ((this._hrstaffname != value))
				{
					this._hrstaffname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hrstaffnumber", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string hrstaffnumber
		{
			get
			{
				return this._hrstaffnumber;
			}
			set
			{
				if ((this._hrstaffnumber != value))
				{
					this._hrstaffnumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdate", DbType="DateTime NOT NULL")]
		public System.DateTime createdate
		{
			get
			{
				return this._createdate;
			}
			set
			{
				if ((this._createdate != value))
				{
					this._createdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lasteditdate", DbType="DateTime NOT NULL")]
		public System.DateTime lasteditdate
		{
			get
			{
				return this._lasteditdate;
			}
			set
			{
				if ((this._lasteditdate != value))
				{
					this._lasteditdate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_TargetEntries")]
	public partial class Tb_TargetEntry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _entry_key;
		
		private string _workflowid;
		
		private int _requeststageid;
		
		private string _requeststage;
		
		private System.DateTime _requestdate;
		
		private string _employee_number;
		
		private string _name;
		
		private string _grade;
		
		private string _deptname;
		
		private string _deptcode;
		
		private string _cabal;
		
		private string _cabal_l;
		
		private string _sabal;
		
		private string _sabal_l;
		
		private string _fx;
		
		private string _rv;
		
		private string _fd;
		
		private string _inc;
		
		private string _inc_l;
		
		private System.DateTime _createdt;
		
		private string _target_status;
		
		private string _hr_uploader_name;
		
		private string _hr_uploader_id;
		
		private string _appperiod;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onentry_keyChanging(string value);
    partial void Onentry_keyChanged();
    partial void OnworkflowidChanging(string value);
    partial void OnworkflowidChanged();
    partial void OnrequeststageidChanging(int value);
    partial void OnrequeststageidChanged();
    partial void OnrequeststageChanging(string value);
    partial void OnrequeststageChanged();
    partial void OnrequestdateChanging(System.DateTime value);
    partial void OnrequestdateChanged();
    partial void Onemployee_numberChanging(string value);
    partial void Onemployee_numberChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OngradeChanging(string value);
    partial void OngradeChanged();
    partial void OndeptnameChanging(string value);
    partial void OndeptnameChanged();
    partial void OndeptcodeChanging(string value);
    partial void OndeptcodeChanged();
    partial void OncabalChanging(string value);
    partial void OncabalChanged();
    partial void Oncabal_lChanging(string value);
    partial void Oncabal_lChanged();
    partial void OnsabalChanging(string value);
    partial void OnsabalChanged();
    partial void Onsabal_lChanging(string value);
    partial void Onsabal_lChanged();
    partial void OnfxChanging(string value);
    partial void OnfxChanged();
    partial void OnrvChanging(string value);
    partial void OnrvChanged();
    partial void OnfdChanging(string value);
    partial void OnfdChanged();
    partial void OnincChanging(string value);
    partial void OnincChanged();
    partial void Oninc_lChanging(string value);
    partial void Oninc_lChanged();
    partial void OncreatedtChanging(System.DateTime value);
    partial void OncreatedtChanged();
    partial void Ontarget_statusChanging(string value);
    partial void Ontarget_statusChanged();
    partial void Onhr_uploader_nameChanging(string value);
    partial void Onhr_uploader_nameChanged();
    partial void Onhr_uploader_idChanging(string value);
    partial void Onhr_uploader_idChanged();
    partial void OnappperiodChanging(string value);
    partial void OnappperiodChanged();
    #endregion
		
		public Tb_TargetEntry()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entry_key", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string entry_key
		{
			get
			{
				return this._entry_key;
			}
			set
			{
				if ((this._entry_key != value))
				{
					this.Onentry_keyChanging(value);
					this.SendPropertyChanging();
					this._entry_key = value;
					this.SendPropertyChanged("entry_key");
					this.Onentry_keyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workflowid", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string workflowid
		{
			get
			{
				return this._workflowid;
			}
			set
			{
				if ((this._workflowid != value))
				{
					this.OnworkflowidChanging(value);
					this.SendPropertyChanging();
					this._workflowid = value;
					this.SendPropertyChanged("workflowid");
					this.OnworkflowidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requeststageid", DbType="Int NOT NULL")]
		public int requeststageid
		{
			get
			{
				return this._requeststageid;
			}
			set
			{
				if ((this._requeststageid != value))
				{
					this.OnrequeststageidChanging(value);
					this.SendPropertyChanging();
					this._requeststageid = value;
					this.SendPropertyChanged("requeststageid");
					this.OnrequeststageidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requeststage", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string requeststage
		{
			get
			{
				return this._requeststage;
			}
			set
			{
				if ((this._requeststage != value))
				{
					this.OnrequeststageChanging(value);
					this.SendPropertyChanging();
					this._requeststage = value;
					this.SendPropertyChanged("requeststage");
					this.OnrequeststageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requestdate", DbType="DateTime NOT NULL")]
		public System.DateTime requestdate
		{
			get
			{
				return this._requestdate;
			}
			set
			{
				if ((this._requestdate != value))
				{
					this.OnrequestdateChanging(value);
					this.SendPropertyChanging();
					this._requestdate = value;
					this.SendPropertyChanged("requestdate");
					this.OnrequestdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_number", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string employee_number
		{
			get
			{
				return this._employee_number;
			}
			set
			{
				if ((this._employee_number != value))
				{
					this.Onemployee_numberChanging(value);
					this.SendPropertyChanging();
					this._employee_number = value;
					this.SendPropertyChanged("employee_number");
					this.Onemployee_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grade", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string grade
		{
			get
			{
				return this._grade;
			}
			set
			{
				if ((this._grade != value))
				{
					this.OngradeChanging(value);
					this.SendPropertyChanging();
					this._grade = value;
					this.SendPropertyChanged("grade");
					this.OngradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptname", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string deptname
		{
			get
			{
				return this._deptname;
			}
			set
			{
				if ((this._deptname != value))
				{
					this.OndeptnameChanging(value);
					this.SendPropertyChanging();
					this._deptname = value;
					this.SendPropertyChanged("deptname");
					this.OndeptnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptcode", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string deptcode
		{
			get
			{
				return this._deptcode;
			}
			set
			{
				if ((this._deptcode != value))
				{
					this.OndeptcodeChanging(value);
					this.SendPropertyChanging();
					this._deptcode = value;
					this.SendPropertyChanged("deptcode");
					this.OndeptcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cabal", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cabal
		{
			get
			{
				return this._cabal;
			}
			set
			{
				if ((this._cabal != value))
				{
					this.OncabalChanging(value);
					this.SendPropertyChanging();
					this._cabal = value;
					this.SendPropertyChanged("cabal");
					this.OncabalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cabal_l", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cabal_l
		{
			get
			{
				return this._cabal_l;
			}
			set
			{
				if ((this._cabal_l != value))
				{
					this.Oncabal_lChanging(value);
					this.SendPropertyChanging();
					this._cabal_l = value;
					this.SendPropertyChanged("cabal_l");
					this.Oncabal_lChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sabal", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sabal
		{
			get
			{
				return this._sabal;
			}
			set
			{
				if ((this._sabal != value))
				{
					this.OnsabalChanging(value);
					this.SendPropertyChanging();
					this._sabal = value;
					this.SendPropertyChanged("sabal");
					this.OnsabalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sabal_l", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sabal_l
		{
			get
			{
				return this._sabal_l;
			}
			set
			{
				if ((this._sabal_l != value))
				{
					this.Onsabal_lChanging(value);
					this.SendPropertyChanging();
					this._sabal_l = value;
					this.SendPropertyChanged("sabal_l");
					this.Onsabal_lChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fx", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fx
		{
			get
			{
				return this._fx;
			}
			set
			{
				if ((this._fx != value))
				{
					this.OnfxChanging(value);
					this.SendPropertyChanging();
					this._fx = value;
					this.SendPropertyChanged("fx");
					this.OnfxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rv", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string rv
		{
			get
			{
				return this._rv;
			}
			set
			{
				if ((this._rv != value))
				{
					this.OnrvChanging(value);
					this.SendPropertyChanging();
					this._rv = value;
					this.SendPropertyChanged("rv");
					this.OnrvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fd", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fd
		{
			get
			{
				return this._fd;
			}
			set
			{
				if ((this._fd != value))
				{
					this.OnfdChanging(value);
					this.SendPropertyChanging();
					this._fd = value;
					this.SendPropertyChanged("fd");
					this.OnfdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inc", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string inc
		{
			get
			{
				return this._inc;
			}
			set
			{
				if ((this._inc != value))
				{
					this.OnincChanging(value);
					this.SendPropertyChanging();
					this._inc = value;
					this.SendPropertyChanged("inc");
					this.OnincChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inc_l", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string inc_l
		{
			get
			{
				return this._inc_l;
			}
			set
			{
				if ((this._inc_l != value))
				{
					this.Oninc_lChanging(value);
					this.SendPropertyChanging();
					this._inc_l = value;
					this.SendPropertyChanged("inc_l");
					this.Oninc_lChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdt", DbType="DateTime NOT NULL")]
		public System.DateTime createdt
		{
			get
			{
				return this._createdt;
			}
			set
			{
				if ((this._createdt != value))
				{
					this.OncreatedtChanging(value);
					this.SendPropertyChanging();
					this._createdt = value;
					this.SendPropertyChanged("createdt");
					this.OncreatedtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string target_status
		{
			get
			{
				return this._target_status;
			}
			set
			{
				if ((this._target_status != value))
				{
					this.Ontarget_statusChanging(value);
					this.SendPropertyChanging();
					this._target_status = value;
					this.SendPropertyChanged("target_status");
					this.Ontarget_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hr_uploader_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string hr_uploader_name
		{
			get
			{
				return this._hr_uploader_name;
			}
			set
			{
				if ((this._hr_uploader_name != value))
				{
					this.Onhr_uploader_nameChanging(value);
					this.SendPropertyChanging();
					this._hr_uploader_name = value;
					this.SendPropertyChanged("hr_uploader_name");
					this.Onhr_uploader_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hr_uploader_id", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string hr_uploader_id
		{
			get
			{
				return this._hr_uploader_id;
			}
			set
			{
				if ((this._hr_uploader_id != value))
				{
					this.Onhr_uploader_idChanging(value);
					this.SendPropertyChanging();
					this._hr_uploader_id = value;
					this.SendPropertyChanged("hr_uploader_id");
					this.Onhr_uploader_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appperiod", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string appperiod
		{
			get
			{
				return this._appperiod;
			}
			set
			{
				if ((this._appperiod != value))
				{
					this.OnappperiodChanging(value);
					this.SendPropertyChanging();
					this._appperiod = value;
					this.SendPropertyChanged("appperiod");
					this.OnappperiodChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zib_appraisal_approvers")]
	public partial class zib_appraisal_approver : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _entrykey;
		
		private string _unitcode;
		
		private string _unitname;
		
		private string _deptcode;
		
		private string _deptname;
		
		private string _groupcode;
		
		private string _groupname;
		
		private string _supergroupcode;
		
		private string _supergroupname;
		
		private int _roleid;
		
		private string _role;
		
		private string _approverid;
		
		private string _approvername;
		
		private System.DateTime _createdt;
		
		private string _createdbyid;
		
		private System.DateTime _editdate;
		
		private string _edittedbyid;
		
		private string _comments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnentrykeyChanging(string value);
    partial void OnentrykeyChanged();
    partial void OnunitcodeChanging(string value);
    partial void OnunitcodeChanged();
    partial void OnunitnameChanging(string value);
    partial void OnunitnameChanged();
    partial void OndeptcodeChanging(string value);
    partial void OndeptcodeChanged();
    partial void OndeptnameChanging(string value);
    partial void OndeptnameChanged();
    partial void OngroupcodeChanging(string value);
    partial void OngroupcodeChanged();
    partial void OngroupnameChanging(string value);
    partial void OngroupnameChanged();
    partial void OnsupergroupcodeChanging(string value);
    partial void OnsupergroupcodeChanged();
    partial void OnsupergroupnameChanging(string value);
    partial void OnsupergroupnameChanged();
    partial void OnroleidChanging(int value);
    partial void OnroleidChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    partial void OnapproveridChanging(string value);
    partial void OnapproveridChanged();
    partial void OnapprovernameChanging(string value);
    partial void OnapprovernameChanged();
    partial void OncreatedtChanging(System.DateTime value);
    partial void OncreatedtChanged();
    partial void OncreatedbyidChanging(string value);
    partial void OncreatedbyidChanged();
    partial void OneditdateChanging(System.DateTime value);
    partial void OneditdateChanged();
    partial void OnedittedbyidChanging(string value);
    partial void OnedittedbyidChanged();
    partial void OncommentsChanging(string value);
    partial void OncommentsChanged();
    #endregion
		
		public zib_appraisal_approver()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entrykey", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string entrykey
		{
			get
			{
				return this._entrykey;
			}
			set
			{
				if ((this._entrykey != value))
				{
					this.OnentrykeyChanging(value);
					this.SendPropertyChanging();
					this._entrykey = value;
					this.SendPropertyChanged("entrykey");
					this.OnentrykeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string unitcode
		{
			get
			{
				return this._unitcode;
			}
			set
			{
				if ((this._unitcode != value))
				{
					this.OnunitcodeChanging(value);
					this.SendPropertyChanging();
					this._unitcode = value;
					this.SendPropertyChanged("unitcode");
					this.OnunitcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string unitname
		{
			get
			{
				return this._unitname;
			}
			set
			{
				if ((this._unitname != value))
				{
					this.OnunitnameChanging(value);
					this.SendPropertyChanging();
					this._unitname = value;
					this.SendPropertyChanged("unitname");
					this.OnunitnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string deptcode
		{
			get
			{
				return this._deptcode;
			}
			set
			{
				if ((this._deptcode != value))
				{
					this.OndeptcodeChanging(value);
					this.SendPropertyChanging();
					this._deptcode = value;
					this.SendPropertyChanged("deptcode");
					this.OndeptcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string deptname
		{
			get
			{
				return this._deptname;
			}
			set
			{
				if ((this._deptname != value))
				{
					this.OndeptnameChanging(value);
					this.SendPropertyChanging();
					this._deptname = value;
					this.SendPropertyChanged("deptname");
					this.OndeptnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string groupcode
		{
			get
			{
				return this._groupcode;
			}
			set
			{
				if ((this._groupcode != value))
				{
					this.OngroupcodeChanging(value);
					this.SendPropertyChanging();
					this._groupcode = value;
					this.SendPropertyChanged("groupcode");
					this.OngroupcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string groupname
		{
			get
			{
				return this._groupname;
			}
			set
			{
				if ((this._groupname != value))
				{
					this.OngroupnameChanging(value);
					this.SendPropertyChanging();
					this._groupname = value;
					this.SendPropertyChanged("groupname");
					this.OngroupnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supergroupcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string supergroupcode
		{
			get
			{
				return this._supergroupcode;
			}
			set
			{
				if ((this._supergroupcode != value))
				{
					this.OnsupergroupcodeChanging(value);
					this.SendPropertyChanging();
					this._supergroupcode = value;
					this.SendPropertyChanged("supergroupcode");
					this.OnsupergroupcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supergroupname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string supergroupname
		{
			get
			{
				return this._supergroupname;
			}
			set
			{
				if ((this._supergroupname != value))
				{
					this.OnsupergroupnameChanging(value);
					this.SendPropertyChanging();
					this._supergroupname = value;
					this.SendPropertyChanged("supergroupname");
					this.OnsupergroupnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roleid", DbType="Int NOT NULL")]
		public int roleid
		{
			get
			{
				return this._roleid;
			}
			set
			{
				if ((this._roleid != value))
				{
					this.OnroleidChanging(value);
					this.SendPropertyChanging();
					this._roleid = value;
					this.SendPropertyChanged("roleid");
					this.OnroleidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approverid", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string approverid
		{
			get
			{
				return this._approverid;
			}
			set
			{
				if ((this._approverid != value))
				{
					this.OnapproveridChanging(value);
					this.SendPropertyChanging();
					this._approverid = value;
					this.SendPropertyChanged("approverid");
					this.OnapproveridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approvername", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string approvername
		{
			get
			{
				return this._approvername;
			}
			set
			{
				if ((this._approvername != value))
				{
					this.OnapprovernameChanging(value);
					this.SendPropertyChanging();
					this._approvername = value;
					this.SendPropertyChanged("approvername");
					this.OnapprovernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdt", DbType="DateTime NOT NULL")]
		public System.DateTime createdt
		{
			get
			{
				return this._createdt;
			}
			set
			{
				if ((this._createdt != value))
				{
					this.OncreatedtChanging(value);
					this.SendPropertyChanging();
					this._createdt = value;
					this.SendPropertyChanged("createdt");
					this.OncreatedtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdbyid", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string createdbyid
		{
			get
			{
				return this._createdbyid;
			}
			set
			{
				if ((this._createdbyid != value))
				{
					this.OncreatedbyidChanging(value);
					this.SendPropertyChanging();
					this._createdbyid = value;
					this.SendPropertyChanged("createdbyid");
					this.OncreatedbyidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_editdate", DbType="DateTime NOT NULL")]
		public System.DateTime editdate
		{
			get
			{
				return this._editdate;
			}
			set
			{
				if ((this._editdate != value))
				{
					this.OneditdateChanging(value);
					this.SendPropertyChanging();
					this._editdate = value;
					this.SendPropertyChanged("editdate");
					this.OneditdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edittedbyid", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string edittedbyid
		{
			get
			{
				return this._edittedbyid;
			}
			set
			{
				if ((this._edittedbyid != value))
				{
					this.OnedittedbyidChanging(value);
					this.SendPropertyChanging();
					this._edittedbyid = value;
					this.SendPropertyChanged("edittedbyid");
					this.OnedittedbyidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments", DbType="VarChar(100)")]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this.OncommentsChanging(value);
					this.SendPropertyChanging();
					this._comments = value;
					this.SendPropertyChanged("comments");
					this.OncommentsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zib_appraisal_dept_structure")]
	public partial class zib_appraisal_dept_structure
	{
		
		private string _unitcode;
		
		private string _unitname;
		
		private string _deptcode;
		
		private string _deptname;
		
		private string _groupcode;
		
		private string _groupname;
		
		private System.Nullable<int> _hassupergroup;
		
		private string _supergroupcode;
		
		private string _supergroupname;
		
		public zib_appraisal_dept_structure()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string unitcode
		{
			get
			{
				return this._unitcode;
			}
			set
			{
				if ((this._unitcode != value))
				{
					this._unitcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string unitname
		{
			get
			{
				return this._unitname;
			}
			set
			{
				if ((this._unitname != value))
				{
					this._unitname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string deptcode
		{
			get
			{
				return this._deptcode;
			}
			set
			{
				if ((this._deptcode != value))
				{
					this._deptcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string deptname
		{
			get
			{
				return this._deptname;
			}
			set
			{
				if ((this._deptname != value))
				{
					this._deptname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string groupcode
		{
			get
			{
				return this._groupcode;
			}
			set
			{
				if ((this._groupcode != value))
				{
					this._groupcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupname", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string groupname
		{
			get
			{
				return this._groupname;
			}
			set
			{
				if ((this._groupname != value))
				{
					this._groupname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hassupergroup", DbType="Int")]
		public System.Nullable<int> hassupergroup
		{
			get
			{
				return this._hassupergroup;
			}
			set
			{
				if ((this._hassupergroup != value))
				{
					this._hassupergroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supergroupcode", DbType="VarChar(50)")]
		public string supergroupcode
		{
			get
			{
				return this._supergroupcode;
			}
			set
			{
				if ((this._supergroupcode != value))
				{
					this._supergroupcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supergroupname", DbType="VarChar(100)")]
		public string supergroupname
		{
			get
			{
				return this._supergroupname;
			}
			set
			{
				if ((this._supergroupname != value))
				{
					this._supergroupname = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zib_appraisal_approver_roles")]
	public partial class zib_appraisal_approver_role
	{
		
		private string _role;
		
		private int _roleid;
		
		private string _dept;
		
		private string _deptcode;
		
		private string _description;
		
		public zib_appraisal_approver_role()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this._role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roleid", DbType="Int NOT NULL")]
		public int roleid
		{
			get
			{
				return this._roleid;
			}
			set
			{
				if ((this._roleid != value))
				{
					this._roleid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dept", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string dept
		{
			get
			{
				return this._dept;
			}
			set
			{
				if ((this._dept != value))
				{
					this._dept = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string deptcode
		{
			get
			{
				return this._deptcode;
			}
			set
			{
				if ((this._deptcode != value))
				{
					this._deptcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(100)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zib_workflow_master")]
	public partial class zib_workflow_master : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _appid;
		
		private string _workflowid;
		
		private int _requeststageid;
		
		private string _requeststage;
		
		private string _requeststatus;
		
		private System.DateTime _createdt;
		
		private System.DateTime _editdt;
		
		private string _lastapprovername;
		
		private string _lastapprovernumber;
		
		private string _initiatorname;
		
		private string _initiatornumber;
		
		private string _unitname;
		
		private string _unitcode;
		
		private string _deptname;
		
		private string _deptcode;
		
		private string _groupname;
		
		private string _groupcode;
		
		private string _supergroupname;
		
		private string _supergroupcode;
		
		private System.Xml.Linq.XElement _approvalhistory;
		
		private System.Xml.Linq.XElement _audithistory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnappidChanging(string value);
    partial void OnappidChanged();
    partial void OnworkflowidChanging(string value);
    partial void OnworkflowidChanged();
    partial void OnrequeststageidChanging(int value);
    partial void OnrequeststageidChanged();
    partial void OnrequeststageChanging(string value);
    partial void OnrequeststageChanged();
    partial void OnrequeststatusChanging(string value);
    partial void OnrequeststatusChanged();
    partial void OncreatedtChanging(System.DateTime value);
    partial void OncreatedtChanged();
    partial void OneditdtChanging(System.DateTime value);
    partial void OneditdtChanged();
    partial void OnlastapprovernameChanging(string value);
    partial void OnlastapprovernameChanged();
    partial void OnlastapprovernumberChanging(string value);
    partial void OnlastapprovernumberChanged();
    partial void OninitiatornameChanging(string value);
    partial void OninitiatornameChanged();
    partial void OninitiatornumberChanging(string value);
    partial void OninitiatornumberChanged();
    partial void OnunitnameChanging(string value);
    partial void OnunitnameChanged();
    partial void OnunitcodeChanging(string value);
    partial void OnunitcodeChanged();
    partial void OndeptnameChanging(string value);
    partial void OndeptnameChanged();
    partial void OndeptcodeChanging(string value);
    partial void OndeptcodeChanged();
    partial void OngroupnameChanging(string value);
    partial void OngroupnameChanged();
    partial void OngroupcodeChanging(string value);
    partial void OngroupcodeChanged();
    partial void OnsupergroupnameChanging(string value);
    partial void OnsupergroupnameChanged();
    partial void OnsupergroupcodeChanging(string value);
    partial void OnsupergroupcodeChanged();
    partial void OnapprovalhistoryChanging(System.Xml.Linq.XElement value);
    partial void OnapprovalhistoryChanged();
    partial void OnaudithistoryChanging(System.Xml.Linq.XElement value);
    partial void OnaudithistoryChanged();
    #endregion
		
		public zib_workflow_master()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appid", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string appid
		{
			get
			{
				return this._appid;
			}
			set
			{
				if ((this._appid != value))
				{
					this.OnappidChanging(value);
					this.SendPropertyChanging();
					this._appid = value;
					this.SendPropertyChanged("appid");
					this.OnappidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workflowid", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string workflowid
		{
			get
			{
				return this._workflowid;
			}
			set
			{
				if ((this._workflowid != value))
				{
					this.OnworkflowidChanging(value);
					this.SendPropertyChanging();
					this._workflowid = value;
					this.SendPropertyChanged("workflowid");
					this.OnworkflowidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requeststageid", DbType="Int NOT NULL")]
		public int requeststageid
		{
			get
			{
				return this._requeststageid;
			}
			set
			{
				if ((this._requeststageid != value))
				{
					this.OnrequeststageidChanging(value);
					this.SendPropertyChanging();
					this._requeststageid = value;
					this.SendPropertyChanged("requeststageid");
					this.OnrequeststageidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requeststage", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string requeststage
		{
			get
			{
				return this._requeststage;
			}
			set
			{
				if ((this._requeststage != value))
				{
					this.OnrequeststageChanging(value);
					this.SendPropertyChanging();
					this._requeststage = value;
					this.SendPropertyChanged("requeststage");
					this.OnrequeststageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requeststatus", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string requeststatus
		{
			get
			{
				return this._requeststatus;
			}
			set
			{
				if ((this._requeststatus != value))
				{
					this.OnrequeststatusChanging(value);
					this.SendPropertyChanging();
					this._requeststatus = value;
					this.SendPropertyChanged("requeststatus");
					this.OnrequeststatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdt", DbType="DateTime NOT NULL")]
		public System.DateTime createdt
		{
			get
			{
				return this._createdt;
			}
			set
			{
				if ((this._createdt != value))
				{
					this.OncreatedtChanging(value);
					this.SendPropertyChanging();
					this._createdt = value;
					this.SendPropertyChanged("createdt");
					this.OncreatedtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_editdt", DbType="DateTime NOT NULL")]
		public System.DateTime editdt
		{
			get
			{
				return this._editdt;
			}
			set
			{
				if ((this._editdt != value))
				{
					this.OneditdtChanging(value);
					this.SendPropertyChanging();
					this._editdt = value;
					this.SendPropertyChanged("editdt");
					this.OneditdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastapprovername", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string lastapprovername
		{
			get
			{
				return this._lastapprovername;
			}
			set
			{
				if ((this._lastapprovername != value))
				{
					this.OnlastapprovernameChanging(value);
					this.SendPropertyChanging();
					this._lastapprovername = value;
					this.SendPropertyChanged("lastapprovername");
					this.OnlastapprovernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastapprovernumber", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string lastapprovernumber
		{
			get
			{
				return this._lastapprovernumber;
			}
			set
			{
				if ((this._lastapprovernumber != value))
				{
					this.OnlastapprovernumberChanging(value);
					this.SendPropertyChanging();
					this._lastapprovernumber = value;
					this.SendPropertyChanged("lastapprovernumber");
					this.OnlastapprovernumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_initiatorname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string initiatorname
		{
			get
			{
				return this._initiatorname;
			}
			set
			{
				if ((this._initiatorname != value))
				{
					this.OninitiatornameChanging(value);
					this.SendPropertyChanging();
					this._initiatorname = value;
					this.SendPropertyChanged("initiatorname");
					this.OninitiatornameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_initiatornumber", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string initiatornumber
		{
			get
			{
				return this._initiatornumber;
			}
			set
			{
				if ((this._initiatornumber != value))
				{
					this.OninitiatornumberChanging(value);
					this.SendPropertyChanging();
					this._initiatornumber = value;
					this.SendPropertyChanged("initiatornumber");
					this.OninitiatornumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string unitname
		{
			get
			{
				return this._unitname;
			}
			set
			{
				if ((this._unitname != value))
				{
					this.OnunitnameChanging(value);
					this.SendPropertyChanging();
					this._unitname = value;
					this.SendPropertyChanged("unitname");
					this.OnunitnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string unitcode
		{
			get
			{
				return this._unitcode;
			}
			set
			{
				if ((this._unitcode != value))
				{
					this.OnunitcodeChanging(value);
					this.SendPropertyChanging();
					this._unitcode = value;
					this.SendPropertyChanged("unitcode");
					this.OnunitcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string deptname
		{
			get
			{
				return this._deptname;
			}
			set
			{
				if ((this._deptname != value))
				{
					this.OndeptnameChanging(value);
					this.SendPropertyChanging();
					this._deptname = value;
					this.SendPropertyChanged("deptname");
					this.OndeptnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string deptcode
		{
			get
			{
				return this._deptcode;
			}
			set
			{
				if ((this._deptcode != value))
				{
					this.OndeptcodeChanging(value);
					this.SendPropertyChanging();
					this._deptcode = value;
					this.SendPropertyChanged("deptcode");
					this.OndeptcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string groupname
		{
			get
			{
				return this._groupname;
			}
			set
			{
				if ((this._groupname != value))
				{
					this.OngroupnameChanging(value);
					this.SendPropertyChanging();
					this._groupname = value;
					this.SendPropertyChanged("groupname");
					this.OngroupnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string groupcode
		{
			get
			{
				return this._groupcode;
			}
			set
			{
				if ((this._groupcode != value))
				{
					this.OngroupcodeChanging(value);
					this.SendPropertyChanging();
					this._groupcode = value;
					this.SendPropertyChanged("groupcode");
					this.OngroupcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supergroupname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string supergroupname
		{
			get
			{
				return this._supergroupname;
			}
			set
			{
				if ((this._supergroupname != value))
				{
					this.OnsupergroupnameChanging(value);
					this.SendPropertyChanging();
					this._supergroupname = value;
					this.SendPropertyChanged("supergroupname");
					this.OnsupergroupnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supergroupcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string supergroupcode
		{
			get
			{
				return this._supergroupcode;
			}
			set
			{
				if ((this._supergroupcode != value))
				{
					this.OnsupergroupcodeChanging(value);
					this.SendPropertyChanging();
					this._supergroupcode = value;
					this.SendPropertyChanged("supergroupcode");
					this.OnsupergroupcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approvalhistory", DbType="Xml NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement approvalhistory
		{
			get
			{
				return this._approvalhistory;
			}
			set
			{
				if ((this._approvalhistory != value))
				{
					this.OnapprovalhistoryChanging(value);
					this.SendPropertyChanging();
					this._approvalhistory = value;
					this.SendPropertyChanged("approvalhistory");
					this.OnapprovalhistoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_audithistory", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement audithistory
		{
			get
			{
				return this._audithistory;
			}
			set
			{
				if ((this._audithistory != value))
				{
					this.OnaudithistoryChanging(value);
					this.SendPropertyChanging();
					this._audithistory = value;
					this.SendPropertyChanged("audithistory");
					this.OnaudithistoryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zib_workflow_stages")]
	public partial class zib_workflow_stage
	{
		
		private string _appid;
		
		private string _requeststage;
		
		private int _requeststageid;
		
		private int _maxstages;
		
		public zib_workflow_stage()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appid", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string appid
		{
			get
			{
				return this._appid;
			}
			set
			{
				if ((this._appid != value))
				{
					this._appid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requeststage", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string requeststage
		{
			get
			{
				return this._requeststage;
			}
			set
			{
				if ((this._requeststage != value))
				{
					this._requeststage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requeststageid", DbType="Int NOT NULL")]
		public int requeststageid
		{
			get
			{
				return this._requeststageid;
			}
			set
			{
				if ((this._requeststageid != value))
				{
					this._requeststageid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxstages", DbType="Int NOT NULL")]
		public int maxstages
		{
			get
			{
				return this._maxstages;
			}
			set
			{
				if ((this._maxstages != value))
				{
					this._maxstages = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zib_appraisal_user_roles")]
	public partial class zib_appraisal_user_role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _entrykey;
		
		private int _roleid;
		
		private string _role;
		
		private string _username;
		
		private string _employee_number;
		
		private string _name;
		
		private string _status;
		
		private string _description;
		
		private string _createdbyid;
		
		private string _editedbyid;
		
		private System.DateTime _createdt;
		
		private System.DateTime _editdt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnentrykeyChanging(string value);
    partial void OnentrykeyChanged();
    partial void OnroleidChanging(int value);
    partial void OnroleidChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void Onemployee_numberChanging(string value);
    partial void Onemployee_numberChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OncreatedbyidChanging(string value);
    partial void OncreatedbyidChanged();
    partial void OneditedbyidChanging(string value);
    partial void OneditedbyidChanged();
    partial void OncreatedtChanging(System.DateTime value);
    partial void OncreatedtChanged();
    partial void OneditdtChanging(System.DateTime value);
    partial void OneditdtChanged();
    #endregion
		
		public zib_appraisal_user_role()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entrykey", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string entrykey
		{
			get
			{
				return this._entrykey;
			}
			set
			{
				if ((this._entrykey != value))
				{
					this.OnentrykeyChanging(value);
					this.SendPropertyChanging();
					this._entrykey = value;
					this.SendPropertyChanged("entrykey");
					this.OnentrykeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roleid", DbType="Int NOT NULL")]
		public int roleid
		{
			get
			{
				return this._roleid;
			}
			set
			{
				if ((this._roleid != value))
				{
					this.OnroleidChanging(value);
					this.SendPropertyChanging();
					this._roleid = value;
					this.SendPropertyChanged("roleid");
					this.OnroleidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_number", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string employee_number
		{
			get
			{
				return this._employee_number;
			}
			set
			{
				if ((this._employee_number != value))
				{
					this.Onemployee_numberChanging(value);
					this.SendPropertyChanging();
					this._employee_number = value;
					this.SendPropertyChanged("employee_number");
					this.Onemployee_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdbyid", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string createdbyid
		{
			get
			{
				return this._createdbyid;
			}
			set
			{
				if ((this._createdbyid != value))
				{
					this.OncreatedbyidChanging(value);
					this.SendPropertyChanging();
					this._createdbyid = value;
					this.SendPropertyChanged("createdbyid");
					this.OncreatedbyidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_editedbyid", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string editedbyid
		{
			get
			{
				return this._editedbyid;
			}
			set
			{
				if ((this._editedbyid != value))
				{
					this.OneditedbyidChanging(value);
					this.SendPropertyChanging();
					this._editedbyid = value;
					this.SendPropertyChanged("editedbyid");
					this.OneditedbyidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdt", DbType="DateTime NOT NULL")]
		public System.DateTime createdt
		{
			get
			{
				return this._createdt;
			}
			set
			{
				if ((this._createdt != value))
				{
					this.OncreatedtChanging(value);
					this.SendPropertyChanging();
					this._createdt = value;
					this.SendPropertyChanged("createdt");
					this.OncreatedtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_editdt", DbType="DateTime NOT NULL")]
		public System.DateTime editdt
		{
			get
			{
				return this._editdt;
			}
			set
			{
				if ((this._editdt != value))
				{
					this.OneditdtChanging(value);
					this.SendPropertyChanging();
					this._editdt = value;
					this.SendPropertyChanged("editdt");
					this.OneditdtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zib_appraisal_link_role_permission")]
	public partial class zib_appraisal_link_role_permission
	{
		
		private int _role_id;
		
		private int _permission_id;
		
		public zib_appraisal_link_role_permission()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role_id", DbType="Int NOT NULL")]
		public int role_id
		{
			get
			{
				return this._role_id;
			}
			set
			{
				if ((this._role_id != value))
				{
					this._role_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_permission_id", DbType="Int NOT NULL")]
		public int permission_id
		{
			get
			{
				return this._permission_id;
			}
			set
			{
				if ((this._permission_id != value))
				{
					this._permission_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zib_appraisal_user_permission")]
	public partial class zib_appraisal_user_permission
	{
		
		private int _permission_id;
		
		private string _permission_description;
		
		public zib_appraisal_user_permission()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_permission_id", DbType="Int NOT NULL")]
		public int permission_id
		{
			get
			{
				return this._permission_id;
			}
			set
			{
				if ((this._permission_id != value))
				{
					this._permission_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_permission_description", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string permission_description
		{
			get
			{
				return this._permission_description;
			}
			set
			{
				if ((this._permission_description != value))
				{
					this._permission_description = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zib_memo_entries")]
	public partial class zib_memo_entry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _entry_key;
		
		private string _workflowid;
		
		private int _requeststageid;
		
		private string _requeststage;
		
		private System.DateTime _requestdate;
		
		private string _originator_number;
		
		private string _originator_name;
		
		private string _grade;
		
		private string _deptname;
		
		private string _deptcode;
		
		private string _branchname;
		
		private string _branchcode;
		
		private string _unitname;
		
		private string _unitcode;
		
		private string _from;
		
		private string _to;
		
		private string _attn;
		
		private System.DateTime _dateofmemo;
		
		private string _subject;
		
		private string _memobody;
		
		private string _uploadstatus;
		
		private string _ccfields;
		
		private string _approvers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onentry_keyChanging(string value);
    partial void Onentry_keyChanged();
    partial void OnworkflowidChanging(string value);
    partial void OnworkflowidChanged();
    partial void OnrequeststageidChanging(int value);
    partial void OnrequeststageidChanged();
    partial void OnrequeststageChanging(string value);
    partial void OnrequeststageChanged();
    partial void OnrequestdateChanging(System.DateTime value);
    partial void OnrequestdateChanged();
    partial void Onoriginator_numberChanging(string value);
    partial void Onoriginator_numberChanged();
    partial void Onoriginator_nameChanging(string value);
    partial void Onoriginator_nameChanged();
    partial void OngradeChanging(string value);
    partial void OngradeChanged();
    partial void OndeptnameChanging(string value);
    partial void OndeptnameChanged();
    partial void OndeptcodeChanging(string value);
    partial void OndeptcodeChanged();
    partial void OnbranchnameChanging(string value);
    partial void OnbranchnameChanged();
    partial void OnbranchcodeChanging(string value);
    partial void OnbranchcodeChanged();
    partial void OnunitnameChanging(string value);
    partial void OnunitnameChanged();
    partial void OnunitcodeChanging(string value);
    partial void OnunitcodeChanged();
    partial void OnfromChanging(string value);
    partial void OnfromChanged();
    partial void OntoChanging(string value);
    partial void OntoChanged();
    partial void OnattnChanging(string value);
    partial void OnattnChanged();
    partial void OndateofmemoChanging(System.DateTime value);
    partial void OndateofmemoChanged();
    partial void OnsubjectChanging(string value);
    partial void OnsubjectChanged();
    partial void OnmemobodyChanging(string value);
    partial void OnmemobodyChanged();
    partial void OnuploadstatusChanging(string value);
    partial void OnuploadstatusChanged();
    partial void OnccfieldsChanging(string value);
    partial void OnccfieldsChanged();
    partial void OnapproversChanging(string value);
    partial void OnapproversChanged();
    #endregion
		
		public zib_memo_entry()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entry_key", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string entry_key
		{
			get
			{
				return this._entry_key;
			}
			set
			{
				if ((this._entry_key != value))
				{
					this.Onentry_keyChanging(value);
					this.SendPropertyChanging();
					this._entry_key = value;
					this.SendPropertyChanged("entry_key");
					this.Onentry_keyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workflowid", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string workflowid
		{
			get
			{
				return this._workflowid;
			}
			set
			{
				if ((this._workflowid != value))
				{
					this.OnworkflowidChanging(value);
					this.SendPropertyChanging();
					this._workflowid = value;
					this.SendPropertyChanged("workflowid");
					this.OnworkflowidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requeststageid", DbType="Int NOT NULL")]
		public int requeststageid
		{
			get
			{
				return this._requeststageid;
			}
			set
			{
				if ((this._requeststageid != value))
				{
					this.OnrequeststageidChanging(value);
					this.SendPropertyChanging();
					this._requeststageid = value;
					this.SendPropertyChanged("requeststageid");
					this.OnrequeststageidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requeststage", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string requeststage
		{
			get
			{
				return this._requeststage;
			}
			set
			{
				if ((this._requeststage != value))
				{
					this.OnrequeststageChanging(value);
					this.SendPropertyChanging();
					this._requeststage = value;
					this.SendPropertyChanged("requeststage");
					this.OnrequeststageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requestdate", DbType="DateTime NOT NULL")]
		public System.DateTime requestdate
		{
			get
			{
				return this._requestdate;
			}
			set
			{
				if ((this._requestdate != value))
				{
					this.OnrequestdateChanging(value);
					this.SendPropertyChanging();
					this._requestdate = value;
					this.SendPropertyChanged("requestdate");
					this.OnrequestdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_originator_number", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string originator_number
		{
			get
			{
				return this._originator_number;
			}
			set
			{
				if ((this._originator_number != value))
				{
					this.Onoriginator_numberChanging(value);
					this.SendPropertyChanging();
					this._originator_number = value;
					this.SendPropertyChanged("originator_number");
					this.Onoriginator_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_originator_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string originator_name
		{
			get
			{
				return this._originator_name;
			}
			set
			{
				if ((this._originator_name != value))
				{
					this.Onoriginator_nameChanging(value);
					this.SendPropertyChanging();
					this._originator_name = value;
					this.SendPropertyChanged("originator_name");
					this.Onoriginator_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grade", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string grade
		{
			get
			{
				return this._grade;
			}
			set
			{
				if ((this._grade != value))
				{
					this.OngradeChanging(value);
					this.SendPropertyChanging();
					this._grade = value;
					this.SendPropertyChanged("grade");
					this.OngradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptname", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string deptname
		{
			get
			{
				return this._deptname;
			}
			set
			{
				if ((this._deptname != value))
				{
					this.OndeptnameChanging(value);
					this.SendPropertyChanging();
					this._deptname = value;
					this.SendPropertyChanged("deptname");
					this.OndeptnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptcode", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string deptcode
		{
			get
			{
				return this._deptcode;
			}
			set
			{
				if ((this._deptcode != value))
				{
					this.OndeptcodeChanging(value);
					this.SendPropertyChanging();
					this._deptcode = value;
					this.SendPropertyChanged("deptcode");
					this.OndeptcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchname", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string branchname
		{
			get
			{
				return this._branchname;
			}
			set
			{
				if ((this._branchname != value))
				{
					this.OnbranchnameChanging(value);
					this.SendPropertyChanging();
					this._branchname = value;
					this.SendPropertyChanged("branchname");
					this.OnbranchnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branchcode", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string branchcode
		{
			get
			{
				return this._branchcode;
			}
			set
			{
				if ((this._branchcode != value))
				{
					this.OnbranchcodeChanging(value);
					this.SendPropertyChanging();
					this._branchcode = value;
					this.SendPropertyChanged("branchcode");
					this.OnbranchcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitname", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string unitname
		{
			get
			{
				return this._unitname;
			}
			set
			{
				if ((this._unitname != value))
				{
					this.OnunitnameChanging(value);
					this.SendPropertyChanging();
					this._unitname = value;
					this.SendPropertyChanged("unitname");
					this.OnunitnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitcode", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string unitcode
		{
			get
			{
				return this._unitcode;
			}
			set
			{
				if ((this._unitcode != value))
				{
					this.OnunitcodeChanging(value);
					this.SendPropertyChanging();
					this._unitcode = value;
					this.SendPropertyChanged("unitcode");
					this.OnunitcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[from]", Storage="_from", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string from
		{
			get
			{
				return this._from;
			}
			set
			{
				if ((this._from != value))
				{
					this.OnfromChanging(value);
					this.SendPropertyChanging();
					this._from = value;
					this.SendPropertyChanged("from");
					this.OnfromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[to]", Storage="_to", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string to
		{
			get
			{
				return this._to;
			}
			set
			{
				if ((this._to != value))
				{
					this.OntoChanging(value);
					this.SendPropertyChanging();
					this._to = value;
					this.SendPropertyChanged("to");
					this.OntoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attn", DbType="VarChar(100)")]
		public string attn
		{
			get
			{
				return this._attn;
			}
			set
			{
				if ((this._attn != value))
				{
					this.OnattnChanging(value);
					this.SendPropertyChanging();
					this._attn = value;
					this.SendPropertyChanged("attn");
					this.OnattnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateofmemo", DbType="DateTime NOT NULL")]
		public System.DateTime dateofmemo
		{
			get
			{
				return this._dateofmemo;
			}
			set
			{
				if ((this._dateofmemo != value))
				{
					this.OndateofmemoChanging(value);
					this.SendPropertyChanging();
					this._dateofmemo = value;
					this.SendPropertyChanged("dateofmemo");
					this.OndateofmemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string subject
		{
			get
			{
				return this._subject;
			}
			set
			{
				if ((this._subject != value))
				{
					this.OnsubjectChanging(value);
					this.SendPropertyChanging();
					this._subject = value;
					this.SendPropertyChanged("subject");
					this.OnsubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_memobody", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string memobody
		{
			get
			{
				return this._memobody;
			}
			set
			{
				if ((this._memobody != value))
				{
					this.OnmemobodyChanging(value);
					this.SendPropertyChanging();
					this._memobody = value;
					this.SendPropertyChanged("memobody");
					this.OnmemobodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uploadstatus", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string uploadstatus
		{
			get
			{
				return this._uploadstatus;
			}
			set
			{
				if ((this._uploadstatus != value))
				{
					this.OnuploadstatusChanging(value);
					this.SendPropertyChanging();
					this._uploadstatus = value;
					this.SendPropertyChanged("uploadstatus");
					this.OnuploadstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccfields", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ccfields
		{
			get
			{
				return this._ccfields;
			}
			set
			{
				if ((this._ccfields != value))
				{
					this.OnccfieldsChanging(value);
					this.SendPropertyChanging();
					this._ccfields = value;
					this.SendPropertyChanged("ccfields");
					this.OnccfieldsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approvers", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string approvers
		{
			get
			{
				return this._approvers;
			}
			set
			{
				if ((this._approvers != value))
				{
					this.OnapproversChanging(value);
					this.SendPropertyChanging();
					this._approvers = value;
					this.SendPropertyChanged("approvers");
					this.OnapproversChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
